development:
  adapter: postgresql
  encoding: unicode
  database: seedly_development
  pool: 5
  username: seedly
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: seedly_test
  pool: 5
  username: seedly
  password:
